# Generated by Django 3.2.2 on 2021-06-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maqola', '0003_article_kurish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kurish',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
