# Generated by Django 3.2.2 on 2021-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maqola', '0004_alter_article_kurish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kurish',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
