# Generated by Django 3.2.2 on 2021-06-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='author',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='text',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
        migrations.AddField(
            model_name='customuser',
            name='yosh',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
